#列表的创建
#一般的列表都是用中括号内部的元素用逗号隔开
lis=['hello','word',98]#从左向右每个元素可以依次使用0，1，2，...（即为索引）表示，从右向左可以使用-1，-2，-3...表示
print(type(lis))
print(lis)
#也可以使用内置函数来创建列表
lis2=list(['hello','world',98])
print(lis[1])#可以进行获取索引为...的工作
#可以执行列表的查询工作index
print(lis.index('word'))#如果列表中有相同元素只返回元素中的第一个索引
#可以在某一特定区间进行索引
print(lis.index('hello',1,3))
