#python一切皆对象，所有对象都有一个bool值
#获取对象的布尔值可以使用内置函数bool()
'''
以下对象的布尔值为False
False
数值0
空字符串
空列表
空元组
空字典
空集合
'''
#测试对象的bool值
print(bool(False))
print(bool(0))
print(bool(0.0))
print(bool(None))
print(bool(''))
print(bool(""))
print(bool([]))#方括号表示一个空列表
print(bool(list()))#也表示一个空列表
print(bool(()))#小括号表示一个空元组
print(bool(tuple()))#空元组
print(bool({}))#空字典
print(bool(dict()))#空字典
print(bool(set()))#空集合
print("-----以上对象的布尔值为False-----")
print("-----其他对象的布尔值均为True-----")