#字符串又被称为不可变的的字符序列
#可以使用单引号''双引号""三引号来定义"""""""
#单引号和双引号定义的字符串必须在一行
#三引号定义的字符串可以分布在连续多行
str1='雨谢于轩'
print(str1,type(str1))
str2="雨谢于轩"
print(str2,type(str2))
str3="""雨谢于轩"""#三引号可以换行
str4='''雨谢于轩'''
print(str3,type(str3))
print(str4,type(str4))